jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      # এখানে নিশ্চিত করুন যে আপনি আপনার প্রজেক্ট ডিরেক্টরিতে আছেন (যদি প্রয়োজন হয়)
      # যদি আপনার কোড রুট ফোল্ডারেই থাকে, তবে নিচের লাইনটি দরকার নেই
      # - run: cd your_project_folder_name 

      - run: flutter pub get
      - run: flutter build apk --release
